name: 'Keeper Secrets Manager Github Action'
description: 'A GitHub Action to consume secrets from Keeper'
author: 'Keeper Security Inc. <sm@keepersecurity.com>'
inputs:
  keeper-secret-config:
    description: 'Keeper Secrets Manager configuration json or base64 string'
    required: true
  secrets:
    required: true
    description: 'A list of secrets to retrieve from Keeper Vault'
runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: shield
  color: yellow
