name: 'build-test'
on: # rebuild any PRs and main branch changes
  workflow_dispatch:

  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - run: |
          npm install
      - run: |
          npm run all

  test: # make sure the action works on a clean machine without building
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: "Run KSM Action from source"
        uses: ./
        id: ksm
        with:
          keeper-secret-config: ${{ secrets.KSM_ACTION_TEST_CONFIG }}
          secrets: |
            b7K1o8Fwoot8bryzH6pZJg/field/login > username
            b7K1o8Fwoot8bryzH6pZJg/field/password > password
            b7K1o8Fwoot8bryzH6pZJg/file/ch.txt > ./ch1.txt
            b7K1o8Fwoot8bryzH6pZJg/field/login > env:USERNAME
            b7K1o8Fwoot8bryzH6pZJg/field/password > env:PASSWORD
            b7K1o8Fwoot8bryzH6pZJg/file/ch.txt > file:./ch1.txt
      - name: Print secrets
        run: |
          echo "Username is [$USERNAME]"
          reversed=$(echo "$USERNAME" | rev)
          echo "Reversed Username: $reversed"
          echo "Username length is ${#USERNAME}"

      - name: "Run KSM Action from GitHub Marketplace"
        uses: Keeper-Security/ksm-action@master # zizmor: ignore[unpinned-uses] intentional: self-test against deployed master
        id: ksm2
        with:
          keeper-secret-config: ${{ secrets.KSM_ACTION_TEST_CONFIG }}
          secrets: |
            b7K1o8Fwoot8bryzH6pZJg/field/login > username2
            b7K1o8Fwoot8bryzH6pZJg/field/password > password2
            b7K1o8Fwoot8bryzH6pZJg/file/ch.txt > ./ch12.txt
            b7K1o8Fwoot8bryzH6pZJg/field/login > env:USERNAME2
            b7K1o8Fwoot8bryzH6pZJg/field/password > env:PASSWORD2
            b7K1o8Fwoot8bryzH6pZJg/file/ch.txt > file:./ch12.txt
      - name: Print secrets2
        run: |
          echo "Username is [$USERNAME2]"
          reversed=$(echo "$USERNAME2" | rev)
          echo "Reversed Username: $reversed"
          echo "Username length is ${#USERNAME2}"
