name: 'build-test'
on: # rebuild any PRs and main branch changes
  workflow_dispatch:

  pull_request:
  push:
    branches:
      - master

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm install
      - run: |
          npm run all

  test: # make sure the action works on a clean machine without building
    environment: prod
    runs-on: ubuntu-latest
    env:
      # Use repository variable if available, otherwise use default test record UID
      # This can be set in GitHub repository settings under Settings > Secrets and variables > Actions > Variables
      TEST_RECORD_UID: ${{ vars.KSM_TEST_RECORD_UID || 'MC5EQRXjBQMiKidoMQuoSQ' }}
    steps:
      - uses: actions/checkout@v4
      - name: "Run KSM Action from source"
        uses: ./
        id: ksm
        with:
          keeper-secret-config: ${{ secrets.KSM_ACTION_TEST_CONFIG }}
          secrets: |
            ${{ env.TEST_RECORD_UID }}/field/login > username
            ${{ env.TEST_RECORD_UID }}/field/password > password
            ${{ env.TEST_RECORD_UID }}/file/file.txt > ./ch1.txt
            ${{ env.TEST_RECORD_UID }}/field/login > env:USERNAME
            ${{ env.TEST_RECORD_UID }}/field/password > env:PASSWORD
            ${{ env.TEST_RECORD_UID }}/file/file.txt > file:./ch1.txt
      - name: Print secrets
        run: |
          username="${{ steps.ksm.outputs.username }}"
          echo "Username is [$username]"
          reversed=$(echo "$username" | rev)
          echo "Reversed Username: $reversed"
          echo "Username length is ${#username}"

      - name: "Run KSM Action from GitHub Marketplace"
        uses: Keeper-Security/ksm-action@master
        id: ksm2
        with:
          keeper-secret-config: ${{ secrets.KSM_ACTION_TEST_CONFIG }}
          secrets: |
            ${{ env.TEST_RECORD_UID }}/field/login > username2
            ${{ env.TEST_RECORD_UID }}/field/password > password2
            ${{ env.TEST_RECORD_UID }}/file/file.txt > ./ch12.txt
            ${{ env.TEST_RECORD_UID }}/field/login > env:USERNAME2
            ${{ env.TEST_RECORD_UID }}/field/password > env:PASSWORD2
            ${{ env.TEST_RECORD_UID }}/file/file.txt > file:./ch12.txt
      - name: Print secrets2
        run: |
          username="${{ steps.ksm2.outputs.username2 }}"
          echo "Username is [$username]"
          reversed=$(echo "$username" | rev)
          echo "Reversed Username: $reversed"
          echo "Username length is ${#username}"
